Failure # 1 (occurred at 2024-11-24_22-09-30)
[36mray::MultiPPOTrainer.train()[39m (pid=1650751, ip=160.94.128.252, repr=MultiPPOTrainer)
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 355, in train
    raise skipped from exception_cause(skipped)
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 352, in train
    result = self.step()
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 776, in step
    results.update(self._run_one_evaluation(train_future=None))
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 3015, in _run_one_evaluation
    num_recreated = self.try_recover_from_step_attempt(
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 2617, in try_recover_from_step_attempt
    raise error
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 3011, in _run_one_evaluation
    eval_results = eval_func_to_use()
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 966, in evaluate
    batches = ray.get(
ray.exceptions.RayTaskError(Error): [36mray::RolloutWorker.sample()[39m (pid=1651327, ip=160.94.128.252, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fcee0de6b90>)
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 828, in sample
    batches = [self.input_reader.next()]
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 285, in get_data
    item = next(self._env_runner)
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 671, in _env_runner
    active_envs, to_eval, outputs = _process_observations(
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 1056, in _process_observations
    callbacks.on_episode_end(
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/ray/rllib/algorithms/callbacks.py", line 589, in on_episode_end
    callback.on_episode_end(
  File "/home/sarah/Desktop/Eba_ws/HetGPPO/utils.py", line 166, in on_episode_end
    episode.media["rendering"] = wandb.Video(
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/wandb/sdk/data_types/video.py", line 138, in __init__
    self.encode(fps=fps)
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/wandb/sdk/data_types/video.py", line 141, in encode
    mpy = util.get_module(
  File "/home/sarah/miniconda3/envs/hetgppo-env/lib/python3.10/site-packages/wandb/util.py", line 278, in get_module
    raise wandb.Error(required)
wandb.errors.errors.Error: wandb.Video requires moviepy when passing raw data.  Install with "pip install wandb[media]"
